### ISSUE TITLE
MemoryError for high resolution curvilinear grids

### ISSUE THREAD

**Issue by andhuang-CLGX** [regionmask/regionmask#242]
I have some high-res satellite imagery that depends is irregular; lat & lon depends on y, x, or something similar to `xr.tutorial.open_dataset("rasm")`

Then I encountered when I do mask.mask(ds):
`MemoryError: Unable to allocate 6.57 PiB for an array with shape (30412800, 30412800) and data type float64`

due to:
```
~/miniconda3/lib/python3.9/site-packages/regionmask/core/mask.py in _get_LON_LAT_out_shape(lon, lat, fill)
    407         LON, LAT = lon, lat
    408     else:
--> 409         LON, LAT = np.meshgrid(lon, lat)
```

**Comment by mathause** [comment]
`6.57 PiB` is pretty impressive ;-) Yes that should probably not happen. Can you post the repr of the dataset? So that I can see the size, dimensions, and names of the coords and data variables. And the command you use to call mask?

For the rasm dataset you'd have to pass `lat_name` and `lon_name`, so it uses the 2D fields of the coordinates. Maybe you need to pass those?

**Comment by andhuang-CLGX** [comment]
![image](https://user-images.githubusercontent.com/83971150/128069180-0b26eff5-b3fb-45d3-99da-883388b2861d.png)
```
mask = regionmask.from_geopandas(gdf)
mask.mask(ds)
```

**Comment by mathause** [comment]
Thanks! The time dimension in lat an lon is screwing up the detection of the 2D field: 

https://github.com/regionmask/regionmask/blob/f05862cbe8e2d6c9a22b8715e26277415cd0275b/regionmask/core/mask.py#L406

I should fix this internally. But as a workaround you can try:
```python
mask.mask(ds.lon.squeeze(), ds.lat.squeeze())
```

btw: if the `mask` command is too slow  #123 could be of interest for you

**Comment by andhuang-CLGX** [comment]
Thanks! That works
