### ISSUE TITLE
convert radian units to degree automatically

### ISSUE THREAD

**Issue by aaronspring** [regionmask/regionmask#279]
our unstructured ICON grid is stored in radian units, see https://gist.github.com/aaronspring/1b45cf22f80360ddc4ef13af1cadec63, but so far `regionmask` assumes `lon` and `lat` in degrees.

This is how I convert. `np.rad2deg` is also possible.

```python
ds.coords['clon'].attrs,ds.coords['clat'].attrs
({'standard_name': 'longitude',
  'long_name': 'center longitude',
  'units': 'radian',
  'bounds': 'clon_bnds'},
 {'standard_name': 'latitude',
  'long_name': 'center latitude',
  'units': 'radian',
  'bounds': 'clat_bnds'})

def rad_to_deg(ds):
    """Convert radian units to deg."""
    import numpy as np
    #ds.coords.compute()
    with xr.set_options(keep_attrs=True):
        for c in ds.coords:
            if 'units' in ds[c].attrs:
                if ds[c].attrs['units'] == 'radian':
                    print(f'convert {c} from rad to deg')
                    ds[c] = ds[c]* 180./np.pi
                    ds[c].attrs['units'] = 'degrees'
            elif 'bnds' in c:
                print(f'convert {c} from rad to deg')
                ds[c] = ds[c]* 180./np.pi
                ds[c].attrs['units'] = 'degrees'
    return ds
```

The user could do that manually before using `regionmask`. But `regionmask` could also check for radian units itself.

**Comment by aaronspring** [comment]
are you interested in a related PR? What are the api related questions?

shall we assume degrees as default and correct automatically if units are rad or radians?

**Comment by mathause** [comment]
That's a tough one... It feels a bit too magic to me but then again regionmask does wrap longitudes. I would certainly return the original coords in the output mask. I am leaning towards no because it depends on the `.attrs` and those are not super stable in xarray (i.e. they may be lost in some operations [in contrast to the coords names in #280]). But I can be convinced otherwise if it's important for your workflow. [Also I would rather like to reduce the number of keyword arguments.]

The API question are
- do we rely on `ds.lat.attrs.get("units", None) == "radian"` to trigger the conversion or on a keyword?
- If we rely on the `attrs` - do we still add a keword (e.g. `deg_to_rad`) and what is the default?

```python
def rad_to_deg(ds):

    for c in ds.coords:
        if ds[c].attrs.get("units", None) == "radian":
            ds[c] = ds[c]* 180./np.pi
            ds[c].attrs['units'] = 'degrees'
```

**Comment by aaronspring** [comment]
Alternatively we could throw a warning if attrs units is rad or radian because regionmask assumes degrees. That's maybe a less strong intervention
