### ISSUE TITLE
Could you help upgrade the vulnerble dependency in regionmask ? 

### ISSUE THREAD

**Issue by JoeGardner000** [regionmask/regionmask#347]
Hi, @mathause , @aaronspring , I'd like to report a vulnerability issue in **regionmask_0.9.0**.
### Issue Description
I noticed that **regionmask_0.9.0** directly depends on **rasterio_1.2.10**.
However, **rasterio_1.2.10** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. 
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/103017573/162616557-2eeb44c6-434c-44d3-8130-9ca23db52209.png)
### Suggested Vulnerability Patch Versions
**rasterio** has upgraded these vulnerable C libraries to patch versions refer to [issue url](https://github.com/rasterio/rasterio-wheels/issues/80#issue-1194815122).

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (**regionmask** has **9,484** downloads per month), could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
Joe Gardner

**Comment by mathause** [comment]
Thanks, per default it should use the newest version of rasterio, so most (new) users should automatically avoid this problem once the new rasterio version is out. If I understand correctly the problem is present in _all_ versions <= 1.2. I need to think if I will only allow rasterio > 1.2 moving forward. I fear that might be too restrictive as I try to follow NEP 29. I don't think it says anything about avoiding vulnerabilities.

I am also watching the other packages you reported this problem to see what they decide and do as they may have more experience with such issues.
